### ISSUE TITLE
"Recent videos & streams" is always a single video

### ISSUE THREAD

**Issue by Jer-Pha** [sandiegopython/pythonsd-django#140]
Grabbing the video is a loop in [views.py](https://github.com/sandiegopython/pythonsd-django/blob/81b068c61b8f071afce488314e92eba7f89d3deb/pythonsd/views.py#L114) and only the first result is used in [recent-videos.html](https://github.com/sandiegopython/pythonsd-django/blob/81b068c61b8f071afce488314e92eba7f89d3deb/pythonsd/templates/pythonsd/fragments/recent-videos.html#L2). Also, only the id is used by the template, 

Thoughts on changing [get_recent_videos](https://github.com/sandiegopython/pythonsd-django/blob/81b068c61b8f071afce488314e92eba7f89d3deb/pythonsd/views.py#L93) to return a single id as a string, instead of a list of dicts?

Pros:
- Increases performance by eliminating a loop
- Decreases context size - list of dicts --> string
- Reduces template work - no need to slice with |first or use the _with_ tag

Cons
- The current setup would be better if there is a plan to display more than one video (either on the homepage or it's own page e.g. /latest)

I'm not familiar with _defusedxml.ElementTree_ but it would probably look something like this:

`def get_recent_videos(self):`
`    ...`
`    video = ""`
`    if resp.ok:`
`        dom = ElementTree.fromstring(resp.content)`
`        ns = {`
`            "atom": "http://www.w3.org/2005/Atom",`
`            "yt": "http://www.youtube.com/xml/schemas/2015",`
`        }`
`        video = dom.find("atom:entry/yt:videoId", ns)`
`    else:`
`        log.error("Error fetching YouTube video feed")`
`    return video`

I can take care of this if it's seen as a positive change.

**Comment by davidfischer** [comment]
From a performance perspective, the change won't be significant. Fetching the XML feed (or even retrieving from cache) is almost certainly much much much slower than taking the first video with `|first`.

I don't feel particularly strongly but my idea behind caching a list of videos was that we might have a page of more recent meetups and the list/cache could be reused. Since saving 10 videos or 1 to cache doesn't matter much (the time to fetch the videos is probably 2-3 orders of magnitude slower), I figured why not.

**Comment by Jer-Pha** [comment]
Ah, I didn't factor in caching. I assumed the XML was being fetched every page load. If the result is cached, the only change I might suggest is doing the slice when defining the context instead of in the template. I always try to take as much work off of the template engine as possible. We're talking about saving a few ms at best, so this is really a non-issue either way.

**Comment by davidfischer** [comment]
In practice it is probably fetched most of the time since the recent videos are [only cached for 15 minutes](https://github.com/sandiegopython/pythonsd-django/blob/main/pythonsd/views.py#L73) and it's not like we get a lot of traffic.

However there isn't a way to get 1 video significantly faster than 10 because the XML needs to be requested and parsed in the case where it isn't cached. Where it is cached fetching 1 vs 10 (relatively small) dicts from the cache won't make much difference.

I don't feel particularly strongly about any enhancements here one way or the other. Feels fine to pass a context variable of the first video but also probably won't matter much. I do want to keep multiple videos cached though in case we ever have a page with more than 1 recent video which would be easy to add with our existing code.

**Comment by Jer-Pha** [comment]
Closing this issue. The suggested changes would only make sense if there wasn't the possibility of needing multiple videos in the future.
