### ISSUE TITLE
Deploy and replace existing pythonsd.org site

### ISSUE THREAD

**Issue by macro1** [sandiegopython/pythonsd-django#9]
@davidfischer: The proxy site is done, and if we're fine with Heroku free tier hosting is ready to receive requests. You're keeping up the domain registration right?

Heroku deployment hosted here: http://pythonsd.herokuapp.com/

**Comment by davidfischer** [comment]
I am the one who has the domain registration.

I haven't been keeping up with this repository whatsoever. Can you explain what this does differently? I also don't know how I would deploy a new version of this app.

**Comment by treyhunner** [comment]
I think we should pay for Heroku. With the free tier they only allow the site to be live for a certain number of hours per day which means it will take a long time to load unless it's visited every hour or so and if we did have something ping it to keep it alive then it would have about 6 hours per day that it would be offline.

**Comment by macro1** [comment]
On the way this new app functions, it falls back on a proxy view for any patterns it doesn't have (in [pythonsd/urls.py](https://github.com/pythonsd/pythonsd-django/blob/6561679bbd94525c3d8eb2bea0b184e3fdff28e5/pythonsd/urls.py#L11)). Currently aside from the admin and that proxy view, there's nothing here yet.

What that means for you is that you would continue to use the old repository the way you are now until we move those portions of the site. This is what I meant by a hybrid site before. Ideally the proxy would be happening in something like nginx, I know, but this reduces some of the deployment complexity and makes it more obvious to anyone hacking on it what's going on, I think.

Currently the project is hosted by Heroku under my personal account. I should probably add at least one other collaborator so we have some redundancy, and it appears I can do that. For deployment we can either manually deploy the way I have it now, or have CI deploy on successful build on master. I'm fine with either.

**Comment by alaindomissy** [comment]
Interesting

"ping it to keep it alive" is that robust and "industrial" enough ?
I have done that before, not for very long! :-)
Note that the Heroku free tier requires that "the instance must sleep 6
hours in a 24 hour period"
Which 6 hours per 24 hours would we choose? do we want to do that ?

Are we expecting to remain remain with Heroku free rate for a long time?
Otherwise, when and if we do scale:  do we want to pay the Heroku rates ?
How important would it be to benefit from the  the automated on-need
scaling that heroku provides when we decide to start paying ?

How important is it to pay nothing while we don't have much traffic?
Digital Ocean costs $5 fixed per month for this spec:  512MBMemory, 1
CoreProcessor, 20GBSSD Disk, 1TBTransfer
Would these requirements be enough for our initial traffic ?
It looks like the first paying tier on Heroku ("hobby") which does not need
to sleep 6 hours, has min cost of $7 per month but estimated monthly cost
of $57

Heroku has ease of deployment. Is that the main reason to go with Heroku ?
We could use Digital Ocean + Dokku which gives us a very similar deployment
process. Here are a few pointers

http://rogerstringer.com/2015/05/13/make-your-own-heroku/
https://dokku-alt.github.io/
https://github.com/mikexstudios/dokku-nginx-alt

Micah, I 'd be happy to set this up and show you. Interested ?
Also I'd be happy to be your backup on Heroku if needed

Thanks
--Alain

On Wed, Dec 9, 2015 at 6:40 PM, Micah Denbraver notifications@github.com
wrote:

> On the way this new app functions, it falls back on a proxy view for any
> patterns it doesn't have (in pythonsd/urls.py
> https://github.com/pythonsd/pythonsd-django/blob/6561679bbd94525c3d8eb2bea0b184e3fdff28e5/pythonsd/urls.py#L11).
> Currently aside from the admin and that proxy view, there's nothing here
> yet.
> 
> What that means for you is that you would continue to use the old
> repository the way you are now until we move those portions of the site.
> This is what I meant by a hybrid site before. Ideally the proxy would be
> happening in something like nginx, I know, but this reduces some of the
> deployment complexity and makes it more obvious to anyone hacking on it
> what's going on, I think.
> 
> Currently the project is hosted by Heroku under my personal account. I
> should probably add at least one other collaborator so we have some
> redundancy, and it appears I can do that. For deployment we can either
> manually deploy the way I have it now, or have CI deploy on successful
> build on master. I'm fine with either.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonsd/pythonsd-django/issues/9#issuecomment-163467777
> .

## 

--Alain
619-884-5450

**Comment by macro1** [comment]
@alaindomissy / @davidfischer: I have no problems deploying the app wherever. I have some experience with digital ocean with a home-rolled solution using fabric, and I'm sure Dokku wouldn't be too hard to set up. In the grand scheme of things even the 'hobby' tier will probably be fine. I don't think we'll get enough traffic to incur the higher charges.

Let's not get too hung up on the deployment / hosting. I would much rather seen energy put into helping people work on it and developing the app itself.

**Comment by davidfischer** [comment]
It seems we are all on board with this. From what I can see, it looks like the dyno has been switched to hobby ($7/mo - no sleeping). I'm going to see if I can switch the DNS today.

**Comment by davidfischer** [comment]
Alright, I believe I have this worked out. pythonsd.org and pythonsd.com are supposed to forward to www.pythonsd.org. www.pythonsd.org points to Heroku with a CNAME. I'm pretty sure that pythonsd.org is forwarding to www.pythonsd.org but it hasn't propagated yet as it involved an A record change. I'll check back in an hour.

Heroku apparently doesn't do A records which I thought was weird.

**Comment by macro1** [comment]
All looks to be working to me... Thanks @davidfischer.

Let me know if any of you want to be added as collaborators so you can deploy new versions of the app.

**Comment by davidfischer** [comment]
I checked all the forwarding and it seems to be correct. You have already added me as a collaborator.

![screen shot 2015-12-12 at 10 01 34 am](https://cloud.githubusercontent.com/assets/185043/11763224/88675dd2-a0b7-11e5-86e6-d0e91fb7b4f4.png)
